module.exports = {
    siteMetadata: {
        title: `Inter 🌐 Media`,
        titleTemplate: `We design, develop, and teach experiences that make people's lives simpler.`,
        description: `The Business Website for Inter-Global Media Network, Inc.`,
        siteUrl: `https://www.interglobalmedianetwork.com/`,
        image: '/images/profileSmall.png',
        author: `Maria D. Campbell`,
        social: {
            twitter: `letsbsocial1`,
            github: `interglobalmedia`,
            facebook: `mariador62`,
            linkedin: `mariacampbell`,
        },
        twitterUsername: `@letbsoscial1`,
    },
    keywords: [
        'web-development',
        'react',
        'gatsbyjs',
        'google custom search',
        'mongodb',
        'postgresql',
        'nodejs',
        'npm',
        'office 365',
        'dropbox paper',
        'trello',
        'jsx',
        'css in js',
        'styled components',
        'jira',
        'atlassian',
        'git',
        'distributed version control',
        'github',
        'development',
        'production',
        'feature branches',
        'continuous deployment',
        'aws amplify',
        'git integration',
        'css3',
        'html5',
        'audio',
        'video',
        'full stack development',
        'front end development',
        'back end development',
        'automated workflows',
        'aws',
        'netlify',
        'gh pages',
        'heroku',
        'command line',
        'osx',
        'serverless stack',
        'cross browser compatibility',
        'shadow dom',
        'testing',
        'jest testing',
        'html5 canvas',
        'webgl',
        'linting',
        'eslint',
        'prettier',
        'babel',
        'webpack',
        'css modules',
        'sass',
        'node sass',
        'homebrew',
        'responsive design',
        'es6',
        'modern javascript',
        'node security',
        'npm audit fix',
        'snyk',
    ],
    pathPrefix: '/',
    plugins: [
        `gatsby-plugin-sass`,
        `gatsby-plugin-emotion`,
        {
            resolve: `gatsby-source-filesystem`,
            options: {
                path: `${__dirname}/content`,
                name: `blog`,
            },
        },
        {
            resolve: `gatsby-transformer-remark`,
            options: {
                plugins: [
                    {
                        resolve: `gatsby-remark-images`,
                        options: {
                            maxWidth: 1026,
                        },
                    },
                    {
                        resolve: `gatsby-remark-responsive-iframe`,
                        options: {
                            wrapperStyle: `margin-bottom: 1.0725rem`,
                        },
                    },
                    {
                        resolve: `gatsby-remark-prismjs`,
                        options: {
                            classPrefix: 'language-',
                            noInlineHighlight: false,
                        },
                    },
                    `gatsby-remark-copy-linked-files`,
                    `gatsby-remark-smartypants`,
                ],
            },
        },
        `gatsby-transformer-sharp`,
        {
            resolve: `gatsby-source-filesystem`,
            options: {
                name: `images`,
                path: `${__dirname}/src/images`,
            },
        },
        `gatsby-plugin-sharp`,
        {
            resolve: `gatsby-plugin-google-analytics`,
            options: {
                //trackingId: `ADD YOUR TRACKING ID HERE`,
            },
        },
        `gatsby-plugin-feed`,
        {
            resolve: `gatsby-plugin-manifest`,
            options: {
                name: `Gatsby Starter Blog`,
                short_name: `GatsbyJS`,
                start_url: `/`,
                background_color: `#ffffff`,
                theme_color: `#663399`,
                display: `minimal-ui`,
                icon: `src/images/gatsby-icon.png`,
            },
        },
        `gatsby-plugin-offline`,
        `gatsby-plugin-react-helmet`,
        {
            resolve: `gatsby-plugin-typography`,
            options: {
                pathToConfigModule: `src/utils/typography`,
            },
        },
    ],
}
