backend:
    name: git-gateway
    branch: master

media_folder: static/img
public_folder: /img

collections:
    - name: 'blog'
      label: 'Blog'
      folder: 'content/blog'
      create: true
      slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
      editor:
          preview: false
      fields:
          - {label: Title, name: title}
          - {label: Date, name: date, widget: date}
          - {label: Description, name: description, widget: description}
          - {label: Image, name: image, widget: image}
          - {label: Body, name: body, widget: markdown}
          - {label: Tags, name: tags, widget: list}
          - {label: Categories, name: categories, widget: list}
